site_name: MeasureIt_ARCH Docs
site_url: https://kevancress.github.io/MeasureIt_ARCH/
extra_css: [extra.css]
repo_url: https://github.com/kevancress/MeasureIt_ARCH
edit_uri: edit/development/docs/docs/

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - Introduction:
        - Features & UI: intro/features.md
        - FAQ: intro/faq.md

    - Tutorials:
        - Installing MeasureIt_ARCH: tutorials/install.md
        - Creating a drawing set with MeasureIt_ARCH: tutorials/drawing_set.md
        - Set up a Titleblock with MeasureIt_ARCH: tutorials/titleblock_setup.md
        - Draw a Wall assembly with Dynamic Line Groups: tutorials/line_group_tut.md
        - Section Drawing with MeasureIt_ARCH Hatches: tutorials/section_hatches.md
        - Batch convert .svg's to .pdf's: tutorials/svg_to_pdf.md

    - Property Descriptions:
        - Dimensions: prop_descriptions/dimensions.md
        - Line Groups: prop_descriptions/linegroups.md
        - Annotations: prop_descriptions/annotations.md
        - Views: prop_descriptions/views.md
        - Hatches: prop_descriptions/hatches.md
        - Text Fields: prop_descriptions/textfields.md
        - Rendering: prop_descriptions/render.md

    - Contributions:
        - Reporting Issues: contributions/issue_reports.md
        - Requesting Features: contributions/feature_requests.md
        - Contributing Code: contributions/contributing_code.md
        
theme: readthedocs